### ISSUE TITLE
Sensors don't always refresh after HA restart

### ISSUE THREAD

**Issue by HarvsG** [habuild/hassio-addons#54]
https://github.com/habuild/hassio-addons/blob/4a33e0fae5350dafc7e57392493f3a48dc17c37f/triinv-sbfspot/Dockerfile#L91

When I restarted my home assistant after dark, all of my entities were unavailable. HAOS-SBFspot, I suspect it is because this line ran before the mosquito broker was up. When I then restarted HAOS-SBFspot, they started working.

**Comment by habuild** [comment]
See post 260 for more info
https://community.home-assistant.io/t/sbfspot-bluetooth-homeassistant-addon/402671/260?u=hasqt
